Les plus grands postes d'artificialisation :
```{r}
statAix <- getStatsComm(f, "13001")

surfaceAix <- statAix %>% filter(variable == "surfcom20") %>% pull(value)

myRow <- statAix %>% 
  filter(str_detect(variable, "^art")) %>% 
  arrange(desc(value)) %>% 
  head(1) %>% 
  select(variable, value)

type <- gsub("art(\\S+)0920", "\\1", myRow$variable)
value <- myRow$value / surfaceAix

print(type)
print(value)

```
Créons une fonction :
```{r}
getMajorChange <- function(f, codeInsee) {
  myStats <- getStatsComm(f, codeInsee)
  
  mySurface <- myStats %>% filter(variable == "surfcom20") %>% pull(value)
  
  myRow <- myStats %>% 
    filter(str_detect(variable, "^art")) %>% 
    arrange(desc(value)) %>% 
    head(1) %>% 
    select(variable, value)
  
  type <- gsub("art(\\S+)0920", "\\1", myRow$variable)
  value <- myRow$value / mySurface
  
  return(list(type = type, value = value))
}

f$majorType <- NA
f$majorValue <- NA
for(i in 1:nrow(f)) {
  codeInsee <- f$idcom[i]
  res <- getMajorChange(f, codeInsee)
  f$majorType[i] <- res$type
  f$majorValue[i] <- res$value
}
```