---
title: "OpenData (Exos)"
subtitle: "Votre mission, si vous l'acceptez"
author: "CEREMA Med > Mathieu Rajerison"
date: "<span style='font-size:0.5em;'>06/02/2019</span>"
output:
  xaringan::moon_reader:
    css: ["../css/my_css.css", "../css/my_css_session2.css", "default", "default-fonts"]
    seal: true
    lib_dir: libs
    self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```

# Feuille de route
L'environnement et notre espace de vie nous intéressent particulièrement.

Vous êtes invités à une réunion pour parler de l'environnement en PACA, notamment sur les volets **qualité de l'air**, le **bruit** et la **pollution**, et il est attendu de vous des éléments factuels bien illustrés.

--

- Quelles sont les différentes étapes d'investigation ?

--

- Sur quel(s) portail(s) iriez-vous chercher des informations ou données ?

---
# Les étapes
Voici les différentes étapes de l'exercice :

`r fa("walking", width = "2em")`  Dans un premier temps, nous **accèderons** au jeu de données et en **prendrons connaissance**.

--

`r fa("book-reader", width = "2em")`  Dans un second temps, nous les **explorerons** afin de répondre à des questions précises

--

`r fa("glasses", width = "2em")`  Dans un troisième temps, nous les **visualiserons** à l'aide de graphiques

--

`r fa("map-marked", width = "2em")`  Dans un quatrième temps, nous prendrons une donnée spatiale que nous **cartographierons**.