---
title: "OpenData (Exos)"
subtitle: "Accès au terrain et repérages"
author: "CEREMA Med > Mathieu Rajerison"
date: "<span style='font-size:0.5em;'>06/02/2019</span>"
output:
  xaringan::moon_reader:
    css: ["../css/my_css.css", "../css/my_css_session2.css", "default", "default-fonts"]
    seal: true
    lib_dir: libs
    self_contained: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```

class: center, middle, inverse
# Accéder au jeu de données

`r fa("walking", width = "3em")`
---
class: exo
## Exo 1

&#9658; Partez à la recherche d'un jeu de données (datasets) sur DataSud sur `r fa("file", width = "1em")` les indicateurs de développement durable portant sur les déplacements, la qualité de l'air, l'exposition au bruit

---
### Réponse :
`r fa("file", width = "1em")` [Dataset épanouissement](https://trouver.datasud.fr/dataset/epanouissement-de-tous-les-etres-humains-indicateurs-de-developpement-durable)

---
class: center, middle, inverse
# Interpréter les méta-données
### Tâter, lire le terrain

`r fa("book-reader", width = "3em")`

---
class: center, middle, inverse
# Quelles questions posez-vous à quelqu'un que vous venez de rencontrer ?

---

Les premières questions à se poser, quand on rencontre un jeu de données, sont les suivantes :

- **Qui** a produit la donnée ?

--

- **Quand** a-t-elle été produite et est-elle suffisamment récente pour l'usage que je veux en faire ?

--

- Quelle est son **emprise géographique** (si elle existe) et quel est son niveau de **granularité** (commune, département, région, interco ?)

--

- S'il est possible de le savoir, quel a été **le mode de production** de la donnée ?

--

- Après ouverture, paraît-elle d'assez bonne **qualité** ?

--

- Le fichier de **méta-données** décrit-il suffisamment bien l'ensemble des variables présentes ?

`r fa("readme", width = "1em")` [Lire l'article d'infolabs sur l'interview de la donnée](https://infolabs.io/interview-de-la-donnee)

---
class: exo

## Exo 2

&#9658; `r fa("file", width = "1em")` Pour ce jeu de données, les premières questions à se poser sont les suivantes :

1. Qui est l'**auteur** de la donnée ? Semble-t-il être de confiance ? Si j'ai une question à poser sur cette donnée, qui contacter ? (Question *qui*)

--

2. De **quand** datent les données ? Puis-je disposer de la donnée d'il y a un mois ? (Question *quand*)<!-- créées le 05 07 2017 avec fréquence annuelle-->

--

3. Sous quel **format** les données ont-elles été mises à disposition ? Est-il le meilleur ? <!--ODS CLS-->

--

4. Sous **quelles conditions** puis-je utiliser ces données ? <!-- LO-->

---
class: center, middle, inverse
# Pré-visualiser la donnée
### Sonder le terrain  

`r fa("glasses", width = "3em")`

---
## Outils

Les outils CSV Good Generator d'Etalab et [CSVLint](https://csvlint.io/) permettent de contrôler la qualité des données.

[WTFCSV](https://databasic.io/en/wtfcsv/) permet d'avoir un aperçu rapide des données.